services:
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/DockerFile
    volumes:
      - .:/var/www/html
    expose:
      - 9000

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/DockerFile
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php